### ISSUE TITLE
Basic XPath calculation broken

### ISSUE THREAD

**Issue by dcreese** [dcawston/datareaper#1]
Broken since b9ae5c0a4e348f39aa52defbca7bb6774b3fbbe5 - 29/06/2015

**Comment by m-hex** [comment]
Fixed in 3661e32087db081582aec9b193b1b46acd328865

How you activate it is a bit weird (because I've not implemented the select button just yet) but if you add a new XPath and then close the sidebar and select the element you want, it'll calculate and display the result.
